/* ============================================================
   SAT PrepMe, strategy and trap taxonomy

   Two catalogs plus one annotation map:

   STRATS the move a question is testing whether you make
   TRAPS the trick each wrong answer was built from
   TAGS qid -> { strat, traps: {choiceIndex: trapId} }

   The point of the taxonomy is diagnosis. Skill accuracy tells you
   *what topic* is weak; strategy and trap data tell you *what she is
   doing wrong*, which is the thing you can actually coach.
   ============================================================ */

/* ---------------- strategy families ---------------- */
window.STRATS = {
  /* Reading and Writing */
  'predict-first': { section:'rw', name:'Predict, then match',
    move:'Say the answer in your own words before you read a single choice, then look for the choice closest to what you said.',
    why:'Once you read four polished choices, all four start to sound reasonable. Your own prediction gives you something to measure them against.',
    drill:'Cover the choices with your hand. Write your prediction in five words. Then uncover.' },
  'claim-fit': { section:'rw', name:'Make the evidence fit the exact claim',
    move:'Put the claim in your own words, list what it needs to be true, then ask whether the choice actually props that up or knocks it down.',
    why:'You win these by being precise about the claim, not by picking whichever option sounds the most scientific.',
    drill:'Before you look at choices, write the claim down and underline the task word: support, or weaken.' },
  'data-discipline': { section:'rw', name:'Read the units, then do the math',
    move:'Read the axis labels first. A relationship needs two data points. A "most" or "steepest" needs you to actually compute every group.',
    why:'These look like reading questions but they are arithmetic. Eyeballing the chart is exactly how they catch you.',
    drill:'Jot the numbers you need in the margin before you read any choice.' },
  'smallest-step': { section:'rw', name:'Take the smallest step you can prove',
    move:'Pick the most modest thing the text fully supports. No outside knowledge, even if you know it is true.',
    why:'An inference is one small step past the text. The dramatic conclusion is nearly always the wrong one.',
    drill:'For each choice ask: which words in the text prove this? If you cannot point at them, cross it off.' },
  'context-word': { section:'rw', name:'Let the sentence pick the word',
    move:'Put your own word in the blank first. Use the colon, the dash, or the contrast that the sentence hands you.',
    why:'The most common meaning of the word is sitting right there in the choices on purpose. The sentence decides, not the dictionary.',
    drill:'Slot your choice back in and read the whole sentence out loud.' },
  'author-move': { section:'rw', name:'Name what the author is doing',
    move:'Answer with a verb: describing, correcting, conceding, redirecting. For an underlined sentence, read the sentence before and after it.',
    why:'These ask about how the text is built, not what it says. A choice can be true about the content and still name the wrong move.',
    drill:'Sum up each sentence in three words, then count the moves you get.' },
  'concession-map': { section:'rw', name:'Split what they accept from what they reject',
    move:'Write down what the second author agrees with and what they push back on. Any choice attacking the part they agree with is gone.',
    why:'Real disagreement between two writers is usually narrow. Choices that blow it up into total rejection are the standard trap.',
    drill:'Underline every "grants," "does not dispute," and "admits" in the second text.' },
  'relationship-first': { section:'rw', name:'Name the relationship first',
    move:'Decide which of four things is happening between the sentences before you look at the choices: same direction, opposite, cause, or example.',
    why:'Transition words blur together when you shop through them. Name the logic first and the choice becomes obvious.',
    drill:'Cover the choices and say out loud: these two sentences agree, clash, cause, or illustrate.' },
  'goal-checklist': { section:'rw', name:'Treat the goal as a checklist',
    move:'Break the stated goal into parts and make the choice tick every one.',
    why:'All the notes are true, so being accurate cannot separate the choices. Only the goal can.',
    drill:'Underline the goal and number its parts before you read anything else.' },
  'boundary-test': { section:'rw', name:'Test each side for a full sentence',
    move:'Cover the punctuation and ask whether each side could stand alone, then pick the only mark that is allowed to join them.',
    why:'Punctuation is structural, not musical. Where you would pause while reading is not evidence.',
    drill:'Say "complete" or "incomplete" out loud for each side before you choose.' },
  'grammar-strip': { section:'rw', name:'Strip the sentence, then apply the rule',
    move:'Cross out the modifiers to find the bare subject and verb, then apply the one rule being tested: agreement, tense, apostrophe, modifier, parallelism, or comparison.',
    why:'Long sentences hide simple errors. Once you strip them down, the rule is usually easy to see.',
    drill:'Physically cross out every "of" phrase and everything between commas.' },

  /* Math */
  'translate': { section:'math', name:'Turn the words into equations',
    move:'Write "let x = ..." every time, then build one equation per condition. Convert units before you substitute anything.',
    why:'Most word problems go wrong in the setup, not the algebra.',
    drill:'Label every number with its unit as you write it down.' },
  'solve-check': { section:'math', name:'Solve it, then check it',
    move:'Undo the operations in reverse order, then put your answer back into the original equation.',
    why:'Checking takes ten seconds and catches sign errors, extraneous roots, and stopping one step early.',
    drill:'Never leave an equation without substituting your answer back in once.' },
  'systems-tactics': { section:'math', name:'Pick the cheaper way through a system',
    move:'Eliminate when a variable cancels for free. Substitute when a coefficient is already 1. Then re-read what was actually asked for.',
    why:'Systems questions love to ask for x + y, or for the variable you did not solve for first.',
    drill:'Circle the quantity you need before you start solving.' },
  'expression-structure': { section:'math', name:'Look at the shape of the expression',
    move:'Spot the structure first: difference of squares, perfect square, common base. Then use the exponent or factoring rule that fits.',
    why:'These reward recognizing a shape more than grinding through steps.',
    drill:'Ask "what shape is this?" before you touch it, then test your result with x = 2.' },
  'function-notation': { section:'math', name:'Substitute in parentheses, inside out',
    move:'Put the input in parentheses. For a composition, work out the inner value and write it on its own line before you use it.',
    why:'Nearly every miss here is a sign error or a reversed order, and one extra line prevents both.',
    drill:'Write the middle value down. Do not do it in your head.' },
  'function-behavior': { section:'math', name:'Use how the function behaves',
    move:'Vertex at x = -b/2a. Discriminant for how many solutions. Sum of roots is -b/a. Growth factor and period for exponentials.',
    why:'These shortcuts answer the question without solving it, as long as you then report the thing that was asked for.',
    drill:'After you find the vertex x, stop and ask whether the question wants x or the value there.' },
  'proportional-reasoning': { section:'math', name:'Think in rates, ratios, and percents',
    move:'Percent change is change over the original. Two percent changes multiply, they never add. Convert every unit before you divide.',
    why:'The traps here are structural: wrong denominator, added percents, a missed conversion.',
    drill:'Write the units into the fraction and cancel them on the page.' },
  'data-inference': { section:'math', name:'Know what a statistic is allowed to say',
    move:'Find the condition, because it sets the denominator. Ask which measure an outlier moves. Remember a margin of error gives you a range, not a fact.',
    why:'These test whether you can say what the number means, not whether you can compute it.',
    drill:'Say the statistic back as a full sentence, including which group it describes.' },
  'geometry-toolkit': { section:'math', name:'Find the radius, open the formula sheet',
    move:'Route circle problems through the radius. Take trig ratios relative to the angle named. Scale with symbols, not numbers. Use the angle relationship the figure gives you.',
    why:'The formula sheet is provided. The actual skill is knowing which tool the figure is asking for.',
    drill:'Label the figure with everything you know before you write an equation.' },
  'coordinate-geometry': { section:'math', name:'Work in the coordinate plane',
    move:'Slope is rise over run with both points in the same order. Parallel means equal slopes. Complete the square to read a circle out of its equation.',
    why:'Parallel versus perpendicular, and rise versus run, are the two places this reliably slips.',
    drill:'Label your two points before you subtract, and sketch it when you can.' },
  'choice-tactics': { section:'math', name:'Use the answer choices',
    move:'Back-solve by testing the choices, or plug in a number like x = 2 on "which expression is equivalent" questions.',
    why:'On some questions, testing four choices is genuinely faster and safer than doing the algebra.',
    drill:'Before you solve, ask yourself whether you could just test the choices instead.' }
};

/* ---------------- trap catalog ---------------- */
window.TRAP_FAMILIES = {
  scope:     { name:'Scope', blurb:'The choice says more, or less, than the text lets you say.' },
  partial:   { name:'Half the job', blurb:'The choice does part of what you were asked and stops.' },
  direction: { name:'Backwards', blurb:'The right idea, pointed the wrong way round.' },
  referent:  { name:'Wrong thing', blurb:'A fine statement about something other than what you were asked.' },
  mechanics: { name:'Grammar rule', blurb:'A punctuation or grammar rule that did not get applied.' },
  procedure: { name:'Slipped step', blurb:'A calculation, a formula, or a setup that went wrong.' }
};

window.TRAPS = {
  /* --- scope --- */
  'extreme':        { fam:'scope', name:'Too strong',
    tell:'Watch for only, never, all, none, entirely, proves, at all, in every respect.',
    fix:'SAT texts hedge. When you see an absolute word, go back and check whether the text really goes that far.' },
  'too-narrow':     { fam:'scope', name:'A detail pretending to be the point',
    tell:'A true, specific detail offered to you as the main idea.',
    fix:'Ask whether the choice covers the whole text, especially the last sentence.' },
  'not-in-text':    { fam:'scope', name:'Made up',
    tell:'It sounds like something the passage would say, but no sentence actually says it.',
    fix:'Point at the line. If your finger has nowhere to go, cross it off.' },
  'unstated-cause': { fam:'scope', name:'An invented reason',
    tell:'It slides from a fact to a motive, a need, or an intention the text never gives you.',
    fix:'Keep what happened separate from why. The text has to hand you the why.' },
  'contradicts':    { fam:'scope', name:'The text says the opposite',
    tell:'It often reuses the passage words while flipping what they meant.',
    fix:'Familiar wording is not evidence. Check the claim against the sentence it came from.' },

  /* --- partial --- */
  'half-right':     { fam:'partial', name:'Half right',
    tell:'It nails one thing the question asked for and quietly misses another.',
    fix:'Split the task into parts and tick off every part before you commit.' },
  'one-sided':      { fam:'partial', name:'Only one side',
    tell:'One group, one year, or one species when the claim needs two.',
    fix:'If the claim compares two things, your answer needs both of them in it.' },
  'restates':       { fam:'partial', name:'Repeats instead of explains',
    tell:'It tells you the result again when the question asked why it happened.',
    fix:'"Explain why" needs a mechanism. Saying the effect twice is not a cause.' },
  'one-step-short': { fam:'partial', name:'One step short',
    tell:'A real number from the correct work, just not the final one.',
    fix:'Ask "am I done?" and re-read the last line of the question before you commit.' },
  'wrong-target':   { fam:'partial', name:'Answered a different question',
    tell:'Perfect work, wrong thing reported. x instead of x + y. The vertex x instead of the minimum value. The rate instead of the time.',
    fix:'Circle what is being asked for before you solve, then check your answer against that circle.' },

  /* --- direction --- */
  'reversed':       { fam:'direction', name:'Backwards',
    tell:'Right relationship, wrong way round. Cause and effect swapped, or a rise read as a fall.',
    fix:'Say it as an arrow, A causes B, then check which way the text points it.' },
  'opposite-task':  { fam:'direction', name:'Does the opposite job',
    tell:'It supports when you were asked to weaken, or gives the rival theory prediction.',
    fix:'Underline the task word. On a weaken question, expect a strengthener sitting in the choices.' },
  'wrong-relationship': { fam:'direction', name:'Wrong kind of link',
    tell:'A transition of the wrong type. Contrast where the logic is causal, example where it is opposition.',
    fix:'Name the relationship in plain words before you read the four transition words.' },
  'wrong-order':    { fam:'direction', name:'Right pieces, wrong order',
    tell:'The moves of the text, or the steps of a composition, in the wrong sequence.',
    fix:'Structure questions are about order. Compose from the inside out, and map the text in order.' },
  'flipped-ratio':  { fam:'direction', name:'Upside-down fraction',
    tell:'Run over rise. 15/12 instead of 12/15. The reciprocal of the ratio you want.',
    fix:'Say the numerator and denominator out loud. Sine and cosine can never be bigger than 1.' },
  'sign-slip':      { fam:'direction', name:'Sign error',
    tell:'The right size number with the wrong sign, or a negative dropped while distributing.',
    fix:'Substitute in parentheses, and check one value back in the original equation.' },

  /* --- referent --- */
  'true-but-irrelevant': { fam:'referent', name:'True but beside the point',
    tell:'A correct statement that does not do the job you were asked to do.',
    fix:'Ask "does this accomplish the task?" rather than "is this true?"' },
  'wrong-actor':    { fam:'referent', name:'Wrong person or wrong sentence',
    tell:'The right action done by the wrong thing, or a description of a different part of the text.',
    fix:'Check the subject of the choice against the subject in the text.' },
  'dictionary-default': { fam:'referent', name:'The everyday meaning',
    tell:'Money for "economy". Material for "plastic". The first meaning that comes to mind.',
    fix:'Your own word from the sentence beats the dictionary every time.' },
  'close-but-off':  { fam:'referent', name:'Nearly right',
    tell:'The right neighborhood of meaning with the wrong emphasis. Practicality for spareness, provisional for malleable.',
    fix:'Put your two finalists next to the text, word by word, rather than next to each other.' },
  'misread-data':   { fam:'referent', name:'Misread the chart',
    tell:'Wrong row, wrong group, "more" and "less" flipped, or a difference that turns out to be a tie.',
    fix:'Recompute the comparison from the numbers. Never accept a ranking you did not check.' },
  'wrong-denominator': { fam:'referent', name:'Wrong denominator',
    tell:'It uses the whole table when the question narrowed you to one column, or the sale price instead of the original.',
    fix:'Whatever follows "if" sets the denominator, and percent change divides by the original.' },

  /* --- mechanics --- */
  'comma-splice':   { fam:'mechanics', name:'Comma splice',
    tell:'Two complete sentences held together by nothing but a comma.',
    fix:'Complete plus complete needs a period, a semicolon, or a comma plus and, but, or, so.' },
  'wrong-mark':     { fam:'mechanics', name:'Wrong mark for the job',
    tell:'A real punctuation mark used where the structure needs a different one. A comma before a list, a semicolon before a fragment.',
    fix:'Work out what is on each side first: sentence, list, or fragment. That tells you the mark.' },
  'unpaired':       { fam:'mechanics', name:'Unpaired punctuation',
    tell:'A dash closed off with a comma, or an interrupter that opens and never closes.',
    fix:'Punctuation comes in pairs. Find the opening mark before you pick the closing one.' },
  'split-subject-verb': { fam:'mechanics', name:'Subject cut off from its verb',
    tell:'A lone comma or dash sitting between a long subject and its verb.',
    fix:'Strip the modifiers and put the subject next to its verb. Nothing goes between them.' },
  'agreement-by-ear': { fam:'mechanics', name:'Agreement by ear',
    tell:'The verb matches the nearest noun, or the head count of a collective noun, instead of the real subject.',
    fix:'Cross out every "of" phrase, then match the verb to whatever is left.' },
  'wrong-tense':    { fam:'mechanics', name:'Tense or mood mismatch',
    tell:'A verb form fighting the time markers in the sentence, or an ordinary verb where the subjunctive belongs.',
    fix:'Let the time markers decide. After recommend, require, or insist that, use the base form.' },
  'possessive-count': { fam:'mechanics', name:'Apostrophe in the wrong place',
    tell:'A singular possessive when there are two owners, or a plural with no possessive at all.',
    fix:'Ask how many owners, then whether they own something. Two owners means apostrophe after the s.' },
  'dangling':       { fam:'mechanics', name:'Dangling modifier',
    tell:'An opening phrase describing an action the following subject could not possibly do.',
    fix:'Name the subject right after the comma and check that it can actually do what the phrase describes.' },
  'unparallel':     { fam:'mechanics', name:'Mismatched pair',
    tell:'The second half of "not only ... but also," or one item in a list, in a different grammatical form.',
    fix:'Write the two halves next to each other and match their shapes.' },
  'illogical-comparison': { fam:'mechanics', name:'Comparing unlike things',
    tell:'It compares winters with records, or a thing with a date.',
    fix:'Both sides of "than" have to be the same kind of thing. "Those" usually supplies the missing noun.' },
  'fragment':       { fam:'mechanics', name:'Fragment or run-on',
    tell:'A clause with no real verb, or two clauses jammed together with no mark at all.',
    fix:'Every sentence needs a subject and a verb, and clauses need a legal join.' },
  'sounds-right':   { fam:'mechanics', name:'Sounds fine, breaks the rule',
    tell:'A comma where you would pause. A past tense after a past tense verb. A stray comma after "and".',
    fix:'Trust the structure over your ear, and read the choices character by character.' },

  /* --- procedure --- */
  'unit-miss':      { fam:'procedure', name:'Units ignored',
    tell:'Thousands read as ones. Months used where the model wants years. Degrees treated as a length.',
    fix:'Read the axis labels and the variable definitions before you substitute, and convert first.' },
  'operation-swap': { fam:'procedure', name:'Wrong operation',
    tell:'Divided where you should multiply. Added percents that needed to compound. Subtracted where the model adds.',
    fix:'Predict whether your answer should come out bigger or smaller, then check your operation against that.' },
  'formula-mixup':  { fam:'procedure', name:'Wrong formula',
    tell:'Circumference for area. Lateral surface for volume. Perpendicular slope for parallel. 45-45-90 for 30-60-90.',
    fix:'Open the formula sheet, and name the condition the figure is actually giving you.' },
  'wrong-ratio':    { fam:'procedure', name:'Wrong trig ratio',
    tell:'Cosine reported for sine, or a ratio built from the two legs instead of a leg and the hypotenuse.',
    fix:'Label opposite, adjacent, and hypotenuse for the angle named, then write the ratio.' },
  'extraneous-root':{ fam:'procedure', name:'A root that does not work',
    tell:'A solution of the squared equation that fails in the original, usually by making a square root negative.',
    fix:'Every radical or rational equation gets both candidates checked in the original.' },
  'algebra-rule':   { fam:'procedure', name:'Algebra rule misapplied',
    tell:'Terms canceled instead of factors. Exponents multiplied instead of added. A 2 that never got distributed.',
    fix:'Only whole factors cancel. Test your simplified version against the original with x = 2.' },
  'setup-error':    { fam:'procedure', name:'Set up wrong',
    tell:'Quantities swapped. Growth factor and period reversed. The scale factor applied to the wrong side.',
    fix:'Try your model on one easy input before you trust it.' },
  'arith-slip':     { fam:'procedure', name:'Arithmetic slip',
    tell:'A clean method with one bad number. 180 minus 101. A decimal in the wrong place.',
    fix:'Redo that one calculation, then test the answer back in the question.' }
};

/* ---------------- strategy by RW skill (deterministic) ---------------- */
window.SKILL_STRAT = {
  'Central Ideas and Details':'predict-first',
  'Command of Evidence (Textual)':'claim-fit',
  'Command of Evidence (Quantitative)':'data-discipline',
  'Inferences':'smallest-step',
  'Words in Context':'context-word',
  'Text Structure and Purpose':'author-move',
  'Cross-Text Connections':'concession-map',
  'Transitions':'relationship-first',
  'Rhetorical Synthesis':'goal-checklist',
  'Boundaries':'boundary-test',
  'Form, Structure, and Sense':'grammar-strip'
};

/* ---------------- per-question annotations ----------------
   Each wrong choice is classified by the trick it was built from. */
window.TAGS = {
  /* ---- Reading and Writing ---- */
  rw001:{traps:{0:'extreme',2:'extreme',3:'not-in-text'}},
  rw002:{traps:{0:'half-right',2:'contradicts',3:'true-but-irrelevant'}},
  rw003:{traps:{0:'reversed',2:'contradicts',3:'not-in-text'}},
  rw004:{traps:{0:'not-in-text',2:'not-in-text',3:'contradicts'}},
  rw005:{traps:{1:'extreme',2:'too-narrow',3:'not-in-text'}},
  rw006:{traps:{1:'true-but-irrelevant',2:'true-but-irrelevant',3:'opposite-task'}},
  rw007:{traps:{0:'opposite-task',2:'true-but-irrelevant',3:'opposite-task'}},
  rw008:{traps:{0:'true-but-irrelevant',2:'half-right',3:'close-but-off'}},
  rw009:{traps:{1:'opposite-task',2:'true-but-irrelevant',3:'true-but-irrelevant'}},
  rw010:{traps:{1:'one-sided',2:'one-sided',3:'misread-data'}},
  rw011:{traps:{1:'true-but-irrelevant',2:'one-sided',3:'true-but-irrelevant'}},
  rw012:{traps:{1:'true-but-irrelevant',2:'one-sided',3:'true-but-irrelevant'}},
  rw013:{traps:{1:'one-sided',2:'one-sided',3:'misread-data'}},
  rw014:{traps:{1:'extreme',2:'not-in-text',3:'not-in-text'}},
  rw015:{traps:{0:'contradicts',2:'close-but-off',3:'not-in-text'}},
  rw016:{traps:{0:'extreme',2:'not-in-text',3:'reversed'}},
  rw017:{traps:{0:'extreme',2:'contradicts',3:'reversed'}},
  rw018:{traps:{0:'contradicts',2:'extreme',3:'not-in-text'}},
  rw019:{traps:{0:'reversed',2:'not-in-text',3:'not-in-text'}},
  rw020:{traps:{0:'close-but-off',2:'dictionary-default',3:'close-but-off'}},
  rw021:{traps:{0:'close-but-off',2:'reversed',3:'close-but-off'}},
  rw022:{traps:{0:'dictionary-default',2:'dictionary-default',3:'close-but-off'}},
  rw023:{traps:{1:'contradicts',2:'reversed',3:'not-in-text'}},
  rw024:{traps:{0:'reversed',2:'extreme',3:'dictionary-default'}},
  rw025:{traps:{0:'close-but-off',2:'reversed',3:'close-but-off'}},
  rw026:{traps:{0:'dictionary-default',2:'close-but-off',3:'reversed'}},
  rw027:{traps:{0:'reversed',2:'wrong-actor',3:'not-in-text'}},
  rw028:{traps:{1:'close-but-off',2:'too-narrow',3:'not-in-text'}},
  rw029:{traps:{0:'not-in-text',2:'close-but-off',3:'reversed'}},
  rw030:{traps:{0:'wrong-order',2:'not-in-text',3:'not-in-text'}},
  rw031:{traps:{1:'reversed',2:'close-but-off',3:'reversed'}},
  rw032:{traps:{1:'close-but-off',2:'wrong-actor',3:'not-in-text'}},
  rw033:{traps:{1:'not-in-text',2:'too-narrow',3:'reversed'}},
  rw034:{traps:{0:'extreme',2:'opposite-task',3:'reversed'}},
  rw035:{traps:{1:'extreme',2:'not-in-text',3:'reversed'}},
  rw036:{traps:{0:'contradicts',2:'contradicts',3:'reversed'}},
  rw037:{traps:{0:'contradicts',2:'not-in-text',3:'reversed'}},
  rw038:{traps:{1:'wrong-relationship',2:'wrong-relationship',3:'wrong-relationship'}},
  rw039:{traps:{0:'wrong-relationship',2:'wrong-relationship',3:'wrong-relationship'}},
  rw040:{traps:{0:'wrong-relationship',2:'wrong-relationship',3:'wrong-relationship'}},
  rw041:{traps:{0:'wrong-relationship',2:'wrong-relationship',3:'wrong-relationship'}},
  rw042:{traps:{0:'wrong-relationship',2:'wrong-relationship',3:'wrong-relationship'}},
  rw043:{traps:{0:'wrong-relationship',1:'wrong-relationship',3:'wrong-relationship'}},
  rw044:{traps:{0:'wrong-relationship',2:'wrong-relationship',3:'wrong-relationship'}},
  rw045:{traps:{0:'true-but-irrelevant',2:'true-but-irrelevant',3:'half-right'}},
  rw046:{traps:{0:'half-right',1:'opposite-task',3:'one-sided'}},
  rw047:{traps:{0:'true-but-irrelevant',2:'half-right',3:'half-right'}},
  rw048:{traps:{0:'one-sided',1:'true-but-irrelevant',3:'one-sided'}},
  rw049:{traps:{0:'half-right',2:'close-but-off',3:'restates'}},
  rw050:{traps:{1:'extreme',2:'unstated-cause',3:'close-but-off'}},
  rw051:{traps:{0:'true-but-irrelevant',1:'half-right',3:'half-right'}},
  rw052:{traps:{0:'comma-splice',2:'fragment',3:'sounds-right'}},
  rw053:{traps:{1:'wrong-mark',2:'wrong-mark',3:'wrong-mark'}},
  rw054:{traps:{1:'unpaired',2:'wrong-mark',3:'wrong-mark'}},
  rw055:{traps:{1:'unpaired',2:'wrong-mark',3:'unpaired'}},
  rw056:{traps:{0:'split-subject-verb',2:'wrong-mark',3:'split-subject-verb'}},
  rw057:{traps:{0:'wrong-mark',2:'wrong-mark',3:'wrong-mark'}},
  rw058:{traps:{1:'split-subject-verb',2:'split-subject-verb',3:'wrong-mark'}},
  rw059:{traps:{1:'fragment',2:'wrong-mark',3:'sounds-right'}},
  rw060:{traps:{1:'agreement-by-ear',2:'agreement-by-ear',3:'wrong-tense'}},
  rw061:{traps:{0:'agreement-by-ear',2:'close-but-off',3:'fragment'}},
  rw062:{traps:{0:'wrong-tense',1:'wrong-tense',3:'wrong-tense'}},
  rw063:{traps:{0:'possessive-count',2:'possessive-count',3:'possessive-count'}},
  rw064:{traps:{1:'dangling',2:'dangling',3:'dangling'}},
  rw065:{traps:{0:'unparallel',2:'unparallel',3:'unparallel'}},
  rw066:{traps:{0:'agreement-by-ear',2:'wrong-tense',3:'wrong-tense'}},
  rw067:{traps:{0:'illogical-comparison',2:'illogical-comparison',3:'illogical-comparison'}},
  rw068:{traps:{0:'wrong-tense',2:'sounds-right',3:'fragment'}},

  /* ---- Math ---- */
  m001:{strat:'solve-check', traps:{0:'arith-slip',1:'one-step-short',3:'operation-swap'}},
  m002:{strat:'translate', traps:{0:'wrong-target',2:'unit-miss',3:'close-but-off'}},
  m003:{strat:'solve-check'},
  m004:{strat:'coordinate-geometry', traps:{0:'flipped-ratio',2:'wrong-target',3:'arith-slip'}},
  m005:{strat:'systems-tactics', traps:{0:'wrong-target',1:'wrong-target',3:'wrong-target'}},
  m006:{strat:'translate', traps:{1:'reversed',2:'setup-error',3:'setup-error'}},
  m007:{strat:'systems-tactics', traps:{0:'operation-swap',2:'wrong-target',3:'one-step-short'}},
  m008:{strat:'translate', traps:{1:'setup-error',2:'sign-slip',3:'setup-error'}},
  m009:{strat:'coordinate-geometry', traps:{1:'formula-mixup',2:'sign-slip',3:'setup-error'}},
  m010:{strat:'systems-tactics', traps:{0:'arith-slip',2:'wrong-target',3:'arith-slip'}},
  m011:{strat:'expression-structure'},
  m012:{strat:'choice-tactics', traps:{0:'half-right',2:'half-right',3:'half-right'}},
  m013:{strat:'translate'},
  m014:{strat:'solve-check', traps:{1:'algebra-rule',2:'algebra-rule',3:'operation-swap'}},
  m015:{strat:'solve-check', traps:{0:'sign-slip',2:'one-step-short',3:'wrong-target'}},
  m016:{strat:'systems-tactics'},
  m017:{strat:'translate', traps:{0:'arith-slip',2:'wrong-target',3:'wrong-target'}},
  m018:{strat:'systems-tactics', traps:{0:'arith-slip',2:'arith-slip',3:'wrong-target'}},
  m019:{strat:'data-inference'},
  m020:{strat:'solve-check', traps:{0:'sign-slip',2:'arith-slip',3:'arith-slip'}},
  m021:{strat:'function-notation', traps:{0:'sign-slip',1:'sign-slip',3:'algebra-rule'}},
  m022:{strat:'function-behavior', traps:{0:'setup-error',2:'setup-error',3:'setup-error'}},
  m023:{strat:'expression-structure', traps:{1:'algebra-rule',2:'arith-slip',3:'algebra-rule'}},
  m024:{strat:'function-behavior', traps:{1:'wrong-target',2:'wrong-target',3:'arith-slip'}},
  m025:{strat:'solve-check', traps:{0:'extraneous-root',1:'arith-slip',3:'arith-slip'}},
  m026:{strat:'function-behavior'},
  m027:{strat:'function-notation', traps:{0:'wrong-order',1:'setup-error',3:'sign-slip'}},
  m028:{strat:'expression-structure', traps:{1:'algebra-rule',2:'sign-slip',3:'algebra-rule'}},
  m029:{strat:'function-behavior', traps:{0:'arith-slip',2:'one-step-short',3:'wrong-target'}},
  m030:{strat:'function-behavior'},
  m031:{strat:'function-behavior', traps:{0:'unit-miss',2:'setup-error',3:'setup-error'}},
  m032:{strat:'expression-structure'},
  m033:{strat:'solve-check', traps:{0:'algebra-rule',2:'sign-slip',3:'algebra-rule'}},
  m034:{strat:'translate', traps:{0:'wrong-target',1:'arith-slip',3:'arith-slip'}},
  m035:{strat:'expression-structure'},
  m036:{strat:'function-behavior', traps:{0:'arith-slip',2:'wrong-target',3:'arith-slip'}},
  m037:{strat:'solve-check', traps:{0:'arith-slip',2:'arith-slip',3:'sign-slip'}},
  m038:{strat:'expression-structure', traps:{1:'algebra-rule',2:'algebra-rule',3:'algebra-rule'}},
  m039:{strat:'proportional-reasoning', traps:{0:'wrong-target',2:'wrong-denominator',3:'wrong-target'}},
  m040:{strat:'proportional-reasoning'},
  m041:{strat:'data-inference', traps:{1:'reversed',2:'close-but-off',3:'reversed'}},
  m042:{strat:'data-inference', traps:{0:'wrong-denominator',2:'wrong-target',3:'misread-data'}},
  m043:{strat:'proportional-reasoning', traps:{0:'setup-error',2:'setup-error',3:'one-step-short'}},
  m044:{strat:'proportional-reasoning', traps:{0:'operation-swap',1:'wrong-target',3:'arith-slip'}},
  m045:{strat:'data-inference', traps:{0:'extreme',2:'half-right',3:'extreme'}},
  m046:{strat:'data-inference', traps:{0:'wrong-target',2:'unit-miss',3:'close-but-off'}},
  m047:{strat:'proportional-reasoning'},
  m048:{strat:'proportional-reasoning'},
  m049:{strat:'geometry-toolkit', traps:{1:'arith-slip',2:'wrong-target',3:'wrong-target'}},
  m050:{strat:'geometry-toolkit', traps:{0:'formula-mixup',1:'formula-mixup',3:'formula-mixup'}},
  m051:{strat:'geometry-toolkit', traps:{0:'wrong-ratio',1:'wrong-ratio',3:'flipped-ratio'}},
  m052:{strat:'geometry-toolkit', traps:{0:'formula-mixup',1:'formula-mixup',3:'formula-mixup'}},
  m053:{strat:'geometry-toolkit', traps:{0:'setup-error',1:'setup-error',3:'setup-error'}},
  m054:{strat:'coordinate-geometry'},
  m055:{strat:'geometry-toolkit', traps:{1:'setup-error',2:'formula-mixup',3:'setup-error'}},
  m056:{strat:'geometry-toolkit', traps:{1:'wrong-ratio',2:'wrong-ratio',3:'flipped-ratio'}},
  m057:{strat:'coordinate-geometry'},
  m058:{strat:'geometry-toolkit'},
  m059:{strat:'geometry-toolkit', traps:{0:'sign-slip',2:'formula-mixup',3:'wrong-target'}},
  m060:{strat:'geometry-toolkit', traps:{0:'formula-mixup',2:'wrong-target',3:'flipped-ratio'}}
};

/* resolve the tags for a question */
window.tagsFor = function (q) {
  var t = window.TAGS[q.id] || {};
  return {
    strat: t.strat || window.SKILL_STRAT[q.skill] || null,
    traps: t.traps || {}
  };
};
